apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: namaste-{{ .Values.namespace }}
  labels:
    tier: {{ .Chart.Name }}
spec:
  rules:
    - host: {{ .Values.subdomain }}.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-service
                port:
                  number: {{ .Values.service.port }}
