apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-persistent-volume
  namespace: namaste-{{ .Values.namespace }}
  labels:
    tier: {{ .Chart.Name }}
spec:
  capacity:
    storage: {{ .Values.capacity.storage }}
  hostPath:
    path: /data
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
