apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-persistent-volume-claim
  namespace: namaste-{{ .Values.namespace }}
  labels:
    tier: {{ .Chart.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.capacity.storage }}
