apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: namaste-{{ .Values.namespace }}
  labels:
    tier: {{ .Chart.Name }}
spec:
  type: ClusterIP
  selector:
    tier: {{ .Chart.Name }}
  ports:
    - name: {{ .Values.service.port }}-5432
      port: {{ .Values.service.port }}
      targetPort: 5432
