version: "3.9"
services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10
  api:
    container_name: api
    build:
      context: ./api
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./api:/app
    depends_on:
      db:
        condition: service_healthy
volumes:
  db:
