FROM golang:1.20 AS build

RUN mkdir /app
WORKDIR /app

COPY go.* ./

RUN go mod download

COPY . .

RUN go build -o main main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates libc6-compat

WORKDIR /app

COPY --from=build /app/main /app/.env ./

EXPOSE 8080

CMD [ "./main" ]
